# Site settings
name: 学习交流qq群：727158627；微信群进qq再加；
email: guan_kejian@163.com
author: 层层迷雾
url: https://gkj17.github.io
resume_site: 
github: 
baseurl: ''
description: 提供项目/其他内容的填写这个文档哦：https://docs.qq.com/form/edit/DRVdXTlZPRnZrRWdS            分享pdf电子书链接：https://quqi.gblhgk.com/s/4739256/2zUi3dEpok5hD0g0 当然你也可以发送一些pdf电子书到我的邮箱：guan_kejian@163.com哦  
meta_description: 
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: 层层迷雾

# Build settings
markdown: kramdown

baidu_analysis: 

