# Site settings
name: 学习
email: guan_kejian@163.com
author: 层层迷雾
url: https://gkj17.github.io
resume_site: 
github: 
baseurl: ''
description: 提供项目的填写这个文档哦---->https://docs.qq.com/form/edit/DRVdXTlZPRnZrRWdS
meta_description: 
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: 层层迷雾

# Build settings
markdown: kramdown

baidu_analysis: 

